import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const bmwTypeNextRegular = localFont({
  src: "../public/fonts/BMWTypeNextTT-Regular.woff",
  variable: "--font-bmw-regular",
  weight: "400",
  display: "swap",
});

const bmwTypeNextBold = localFont({
  src: "../public/fonts/BMWTypeNextTT-Bold.woff",
  variable: "--font-bmw-bold",
  weight: "700",
  display: "swap",
});

const bmwTypeNextThin = localFont({
  src: "../public/fonts/BMWTypeNextTT-Thin.woff",
  variable: "--font-bmw-thin",
  weight: "100",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${bmwTypeNextRegular.variable} ${bmwTypeNextBold.variable} ${bmwTypeNextThin.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
